name: vxctl
description: "A Flutter-based setup application for the Vex Project, providing an intuitive interface for configuration, documentation, and installation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  url_launcher: ^6.2.5
  flutter_markdown: ^0.7.7
  flutter_math_fork: ^0.7.1
  markdown: ^7.3.0
  flutter_highlight: ^0.7.0
  shared_preferences: ^2.0.15
  window_size: ^0.1.0
  package_info_plus: ^8.3.0
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/vex_dark.png
    - assets/vex_light.png
    - assets/docs/getting_started.md
    - assets/docs/syntax.md